"""upgrade salary

Revision ID: 64bfb0d77540
Revises: 42c951ddd6fe
Create Date: 2023-06-05 23:32:44.305669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bfb0d77540'
down_revision = '42c951ddd6fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('user', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'salary', ['id'])
    op.create_foreign_key(None, 'salary', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary', type_='foreignkey')
    op.drop_constraint(None, 'salary', type_='unique')
    op.drop_column('salary', 'user')
    # ### end Alembic commands ###
