"""upgrade salary model

Revision ID: c1f73f5f076c
Revises: bbc88f98a22f
Create Date: 2023-06-07 14:55:24.880518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f73f5f076c'
down_revision = 'bbc88f98a22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaryinfo', sa.Column('amount', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'salaryinfo', ['id'])
    op.drop_column('salaryinfo', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaryinfo', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'salaryinfo', type_='unique')
    op.drop_column('salaryinfo', 'amount')
    # ### end Alembic commands ###
